# This is a basic workflow to help you get started with Actions

name: Hello

# Controls when the workflow will run
'on': push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello!"
